In [23]:
#Descarga de datos.
import pandas as pd
ruta = "/home/alejo/Projects/University/Fundamentos-de-la-Ciencia-de-Datos/TP4/movies.csv"
df = pd.read_csv(ruta)
df.head()
#Solución para eliminar los valores NaN
df_limpio = df.dropna()
df_limpio.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
77,The Hitman's Bodyguard,(2017),"\nAction, Comedy, Crime",6.9,"\nThe world's top bodyguard gets a new client,...",\n Director:\nPatrick Hughes\n| \n Stars...,"205,979",118.0,$75.47M
85,Jurassic Park,(1993),"\nAction, Adventure, Sci-Fi",8.1,\nA pragmatic paleontologist visiting an almos...,\n Director:\nSteven Spielberg\n| \n Sta...,"897,444",127.0,$402.45M
95,Don't Breathe,(2016),"\nCrime, Horror, Thriller",7.1,"\nHoping to walk away with a massive fortune, ...",\n Director:\nFede Alvarez\n| \n Stars:\...,"237,601",88.0,$89.22M
111,The Lord of the Rings: The Fellowship of the Ring,(2001),"\nAction, Adventure, Drama",8.8,\nA meek Hobbit from the Shire and eight compa...,\n Director:\nPeter Jackson\n| \n Stars:...,"1,713,028",178.0,$315.54M
125,Escape Room,(I) (2019),"\nAction, Adventure, Horror",6.4,\nSix strangers find themselves in a maze of d...,\n Director:\nAdam Robitel\n| \n Stars:\...,"99,351",99.0,$57.01M

In [35]:
#Correlación entre recaudación(gross) y rating
correlación = df_limpio['RATING'].corr(df_limpio['Gross_Float'])
print(correlación)

0.19192281155702515

In [52]:
#Correlación entre tiempo(RunTime) y año(YEAR)
correlacion = df_limpio['YEAR_limpio'].corr(df_limpio['RunTime'])
print(correlacion)

-0.18940453328165607

In [48]:
#Crear columna YEAR.
df_limpio['YEAR_limpio'] = df_limpio['YEAR'].astype(str).str.replace("(", "").str.replace(")", "").str.replace("I", "").astype(float)

/tmp/ipykernel_25519/3491302529.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_limpio['YEAR_limpio'] = df_limpio['YEAR'].astype(str).str.replace("(", "").str.replace(")", "").str.replace("I", "").astype(float)

In [32]:
#Crear columna gross_float para poder usar para el calculo de otros indicadores
df_limpio['Gross_Float'] = df_limpio['Gross'].str.replace("M", "").str.replace("$","").astype(float).mul(1000000)

/tmp/ipykernel_25519/384995155.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_limpio['Gross_Float'] = df_limpio['Gross'].str.replace("M", "").str.replace("$","").astype(float).mul(1000000)

In [51]:
df_limpio.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,Gross_Float,YEAR_limpio
77,The Hitman's Bodyguard,(2017),"\nAction, Comedy, Crime",6.9,"\nThe world's top bodyguard gets a new client,...",\n Director:\nPatrick Hughes\n| \n Stars...,"205,979",118.0,$75.47M,75470000.0,2017.0
85,Jurassic Park,(1993),"\nAction, Adventure, Sci-Fi",8.1,\nA pragmatic paleontologist visiting an almos...,\n Director:\nSteven Spielberg\n| \n Sta...,"897,444",127.0,$402.45M,402450000.0,1993.0
95,Don't Breathe,(2016),"\nCrime, Horror, Thriller",7.1,"\nHoping to walk away with a massive fortune, ...",\n Director:\nFede Alvarez\n| \n Stars:\...,"237,601",88.0,$89.22M,89220000.0,2016.0
111,The Lord of the Rings: The Fellowship of the Ring,(2001),"\nAction, Adventure, Drama",8.8,\nA meek Hobbit from the Shire and eight compa...,\n Director:\nPeter Jackson\n| \n Stars:...,"1,713,028",178.0,$315.54M,315540000.0,2001.0
125,Escape Room,(I) (2019),"\nAction, Adventure, Horror",6.4,\nSix strangers find themselves in a maze of d...,\n Director:\nAdam Robitel\n| \n Stars:\...,"99,351",99.0,$57.01M,57010000.0,2019.0

In [22]:
# Preprocesamiento de columna GENRE limpiando saltos de línea, corchetes, comillas y barras invertidas
df_limpio['GENRE'] = df_limpio['GENRE'].astype(str).str.replace("\n", "").str.replace("[", "").str.replace("]", "").str.replace("'", "").str.replace('"', '').str.replace("\\", "").str.strip().str.split(", ")

# Explotamos la columna para que cada género tenga su propia fila
df_generos = df_limpio.explode('GENRE')

# Contamos la frecuencia de cada género
conteo = df_generos['GENRE'].value_counts()
print(conteo)

GENRE
 Drama          2613
Comedy          1955
Animation       1723
Drama           1712
 Adventure      1589
Action          1296
Documentary     1222
 Action          962
 Comedy          877
 Mystery         858
 Thriller        844
 Romance         814
 Crime           796
Crime            770
 Fantasy         540
 Family          404
 Horror          394
 History         370
 Sci-Fi          291
 Short           266
Adventure        203
Reality-TV       194
 Sport           186
 Reality-TV      176
Biography        170
 Music           169
Horror           159
 Biography       142
Game-Show         94
Talk-Show         68
Short             67
Thriller          66
 Musical          57
Family            52
 War              47
Romance           39
Fantasy           32
Music             31
Mystery           22
 Talk-Show        21
Sci-Fi            19
 Western          18
 News             18
 Film-Noir        11
 Animation         9
Western            6
Sport              6
News               5
Musical            4
 Game-Show         4
 Documentary       2
History            2
Film-Noir          1
War                1
Name: count, dtype: int64